### ISSUE TITLE
About Us Page is not working!!

### ISSUE THREAD

**Issue by pranavarora1895** [harshitasingh2506/Create.letter#1]
Kindly fix the about us page as it is not working!!

https://harshitasingh2506.github.io/Create.letter/About.html

The name of the file is `about.html`, but in your `index.html` line number 31, you have mentioned **About.html**. Just change it to **about.html**.

Hope that fixes the problem!! Happy Coding!! 😀

**Comment by harshitasingh2506** [comment]
Thank you so much sir....I will fix it asap.
